// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD-lOujSY3lmfwPeAjwCVVM3e-IUQBIZg',
    appId: '1:287776463874:web:3aff1785a24084acda5b1b',
    messagingSenderId: '287776463874',
    projectId: 'urban-advertising-application',
    authDomain: 'urban-advertising-application.firebaseapp.com',
    databaseURL: 'https://urban-advertising-application-default-rtdb.firebaseio.com',
    storageBucket: 'urban-advertising-application.firebasestorage.app',
    measurementId: 'G-QX96NJGNJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwotVs8DyVfqN68fCVoNvGCSQZbLU4qqM',
    appId: '1:287776463874:android:50d50a466d094214da5b1b',
    messagingSenderId: '287776463874',
    projectId: 'urban-advertising-application',
    databaseURL: 'https://urban-advertising-application-default-rtdb.firebaseio.com',
    storageBucket: 'urban-advertising-application.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDD-lOujSY3lmfwPeAjwCVVM3e-IUQBIZg',
    appId: '1:287776463874:web:800bbae06b1d3594da5b1b',
    messagingSenderId: '287776463874',
    projectId: 'urban-advertising-application',
    authDomain: 'urban-advertising-application.firebaseapp.com',
    databaseURL: 'https://urban-advertising-application-default-rtdb.firebaseio.com',
    storageBucket: 'urban-advertising-application.firebasestorage.app',
    measurementId: 'G-R2M6EQ1EZ1',
  );

}